[project]
name = "intel-engine"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "abhyodaya1", email = "abhyodayasingh00@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "groq>=1.7.0",
    "httpx>=0.28.1",
    "python-dotenv>=1.2.3",
    "rich>=15.0.0",
]

[project.scripts]
intel-engine = "intel_engine:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
